site_name: Economicon

theme:
  name: material
  favicon: 
  logo: 
  palette:
    primary: blue
  language: pt

docs_dir: docs/

nav: 
  - Sobre o projeto: index.md
  - Vis√£o Geral: 
      - Problema e Abordagem: Documento_visao/visao.md
      - Aprendizados: Documento_visao/licoes.md
  